## :- Compute the eigenvalues and eigenvectors singular value of a time series data  set.

In [2]:
# importing libraries

import numpy as np
import pandas as pd

In [4]:
# import dataset and visualize data

df = pd.read_csv(r"C:\Users\hp\Desktop\kaggle\student_scores.csv")
print(df)

    Hours  Scores
0     2.5      21
1     5.1      47
2     3.2      27
3     8.5      75
4     3.5      30
5     1.5      20
6     9.2      88
7     5.5      60
8     8.3      81
9     2.7      25
10    7.7      85
11    5.9      62
12    4.5      41
13    3.3      42
14    1.1      17
15    8.9      95
16    2.5      30
17    1.9      24
18    6.1      67
19    7.4      69
20    2.7      30
21    4.8      54
22    3.8      35
23    6.9      76
24    7.8      86


In [5]:
df.shape

(25, 2)

In [6]:
Dataset = df.tail(15)
print(Dataset)

    Hours  Scores
10    7.7      85
11    5.9      62
12    4.5      41
13    3.3      42
14    1.1      17
15    8.9      95
16    2.5      30
17    1.9      24
18    6.1      67
19    7.4      69
20    2.7      30
21    4.8      54
22    3.8      35
23    6.9      76
24    7.8      86


In [7]:
Dataset.shape

(15, 2)

In [8]:
Matrix = np.array(Dataset) 
Matrix

array([[ 7.7, 85. ],
       [ 5.9, 62. ],
       [ 4.5, 41. ],
       [ 3.3, 42. ],
       [ 1.1, 17. ],
       [ 8.9, 95. ],
       [ 2.5, 30. ],
       [ 1.9, 24. ],
       [ 6.1, 67. ],
       [ 7.4, 69. ],
       [ 2.7, 30. ],
       [ 4.8, 54. ],
       [ 3.8, 35. ],
       [ 6.9, 76. ],
       [ 7.8, 86. ]])

In [9]:
Trans = Matrix.transpose()
Trans

array([[ 7.7,  5.9,  4.5,  3.3,  1.1,  8.9,  2.5,  1.9,  6.1,  7.4,  2.7,
         4.8,  3.8,  6.9,  7.8],
       [85. , 62. , 41. , 42. , 17. , 95. , 30. , 24. , 67. , 69. , 30. ,
        54. , 35. , 76. , 86. ]])

In [10]:
New_Matrix = Trans@Matrix
New_Matrix

array([[  460.71,  4915.9 ],
       [ 4915.9 , 52767.  ]])

In [11]:
# Eigenvalues And Eigenvectors.

eig_val, eig_vec = np.linalg.eig(New_Matrix)
print("eigen_value :", eig_val)
print("eigen_vector :", eig_vec)

eigen_value : [2.70947409e+00 5.32250005e+04]
eigen_vector : [[-0.99568799 -0.09276544]
 [ 0.09276544 -0.99568799]]


In [12]:
eig_vec[:,0]

array([-0.99568799,  0.09276544])

In [13]:
eig_vec[:,1]

array([-0.09276544, -0.99568799])

In [14]:
from numpy.linalg import norm
A = New_Matrix@eig_vec[:,0]/norm(New_Matrix@eig_vec[:,0])
B = New_Matrix@eig_vec[:,1]/norm(New_Matrix@eig_vec[:,1])
print(A)
print(B)

[-0.99568799  0.09276544]
[-0.09276544 -0.99568799]


In [15]:
U = np.array([A,B]).T
print(U)

[[-0.99568799 -0.09276544]
 [ 0.09276544 -0.99568799]]


In [16]:
V = np.array(U.T@New_Matrix@eig_vec)
V

array([[ 2.70947409e+00, -1.03588399e-09],
       [ 9.09494702e-13,  5.32250005e+04]])

In [17]:
U@V@eig_vec.T

array([[  460.71,  4915.9 ],
       [ 4915.9 , 52767.  ]])

## Compute SVD by using function.

In [18]:
from numpy.linalg import svd
s,v,d = svd(New_Matrix)
print(svd(New_Matrix))

(array([[-0.09276544, -0.99568799],
       [-0.99568799,  0.09276544]]), array([5.32250005e+04, 2.70947409e+00]), array([[-0.09276544, -0.99568799],
       [-0.99568799,  0.09276544]]))


In [19]:
print(s)

[[-0.09276544 -0.99568799]
 [-0.99568799  0.09276544]]


In [20]:
print(v)

[5.32250005e+04 2.70947409e+00]


In [21]:
print(d)

[[-0.09276544 -0.99568799]
 [-0.99568799  0.09276544]]


## ------------THANK YOU-----------